version: "3.9"

services:
  server:
    build: .
    ports:
      - "1337:1337"

  # db:
  #   image: "postgres"
  #   ports:
  #     - "4321:5432"
  #   environment:
  #     POSTGRES_PASSWORD: "root"
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_DB: "postgres"
